---
- name: Install development tools
  yum: name="@Development tools" state=present

- name: Install prerequisites
  yum: name={{ item }}
  with_items:
    - libpcap
    - libpcap-devel
    - pcre
    - pcre-devel
    - glib2-devel
    - zlib
    - zlib-devel

- name: Download fixbuf
  get_url:
    url: "http://tools.netsa.cert.org/releases/libfixbuf-{{fixbuf_version}}.tar.gz"
    dest: "/tmp/libfixbuf-{{fixbuf_version}}.tar.gz"

- name: Extract fixbuf tarball
  unarchive:
    src: "/tmp/libfixbuf-{{fixbuf_version}}.tar.gz"
    dest: /tmp
    copy: no
    creates: "/tmp/libfixbuf-{{fixbuf_version}}"

- name: Compile and Install fixbuf
  shell: "{{item}}"
  args:
    chdir: "/tmp/libfixbuf-{{fixbuf_version}}"
  with_items:
    - ./configure
    - make
    - make install

- name: Download yaf
  get_url:
    url: "http://tools.netsa.cert.org/releases/yaf-{{yaf_version}}.tar.gz"
    dest: "/tmp/yaf-{{yaf_version}}.tar.gz"

- name: Extract yaf tarball
  unarchive:
    src: "/tmp/yaf-{{yaf_version}}.tar.gz"
    dest: /tmp
    copy: no
    creates: /usr/local/bin/yaf

- name: Compile and install yaf
  shell: "{{item}}"
  args:
    chdir: "/tmp/yaf-{{yaf_version}}"
    creates: /usr/local/bin/yaf
  with_items:
    - ./configure --enable-applabel --enable-plugins
    - make
    - make install

- name: Create yaf service
  shell: "{{item}}"
  args:
    creates: /usr/local/etc/yaf.conf
  with_items:
    - cp /tmp/yaf-{{yaf_version}}/etc/init.d/yaf /etc/init.d/yaf
    - chmod +x /etc/init.d/yaf
    - cp /tmp/yaf-{{yaf_version}}/etc/yaf.conf /usr/local/etc/yaf.conf

- name: Configure yaf
  lineinfile: >
    dest=/usr/local/etc/yaf.conf
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: '^ENABLED=.*$', line: 'ENABLED=1' }
    - { regexp: '^YAF_EXTRAFLAGS=.*$', line: 'YAF_EXTRAFLAGS='}
    - { regexp: '^YAF_CAP_IF=.*$', line: 'YAF_CAP_IF={{ iface }}'}
